version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
  keycloak:
      image: cwa-verification-iam
      restart: always
      environment:
        - DB_VENDOR=${DB_VENDOR}
        - DB_ADDR=${DB_ADDR}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USER=${DB_USER}
        - DB_SCHEMA=${DB_SCHEMA}
        - DB_PASSWORD=${DB_PASSWORD}
        - KEYCLOAK_USER=${KEYCLOAK_USER}
        - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
        - PROXY_ADDRESS_FORWARDING=true
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - "127.0.0.1:18080:8080"
        - "127.0.0.1:18443:8443"
        - "127.0.0.1:17080:7080"
        - "127.0.0.1:17443:7443"
      depends_on:
        - postgres